CREATE TRIGGER "SAPABAP1"."ZBUT0ID" AFTER INSERT ON "SAPABAP1"."BUT0ID" REFERENCING NEW ROW ZBUTID FOR EACH ROW 
BEGIN 
IF :ZBUTID.CLIENT = '010' 
THEN INSERT 
INTO "SAPABAP2"."BUT0ID" VALUES( :ZBUTID.CLIENT,
	 :ZBUTID.PARTNER,
	 :ZBUTID.TYPE,
	 :ZBUTID.IDNUMBER,
	 :ZBUTID.INSTITUTE,
	 :ZBUTID.ENTRY_DATE,
	 :ZBUTID.VALID_DATE_FROM,
	 :ZBUTID.VALID_DATE_TO,
	 :ZBUTID.COUNTRY,
	 :ZBUTID.REGION,
	 :ZBUTID.IDNUMBER_GUID,
	 :ZBUTID.BP_EEW_BUT0ID ) 
;
 
END 
IF 
;
 
END 
;