CREATE TRIGGER "SAPABAP1"."ZJOBGR" AFTER INSERT ON "SAPABAP1"."BUT000" REFERENCING NEW ROW ZJOBGR FOR EACH ROW 
BEGIN 
IF :ZJOBGR.CLIENT = '010' 
THEN INSERT 
INTO "SAPABAP2"."ZBUT000_JOBGR" VALUES( :ZJOBGR.CLIENT,
:ZJOBGR.PARTNER,
:ZJOBGR.JOBGR
) 
;
 
END 
IF 
;
 
END 
;